### ISSUE TITLE
Shifts instead of Mul/div for powers of 2 (bitwise AND instead of Mod)

### ISSUE THREAD

**Issue by maxvogel** [djrieger/mjplusplus#105]

**Comment by maxvogel** [comment]
Could be done during optimizations as well as during code generation, while I think that it should be implemented as optimization in the `LocalOptimizer` or in its own class.

**Comment by ratefuchs** [comment]
There's a problem with doing it too early (e.g. in LocalOptimizer): we have to take care of new type of nodes during other optimizations.
We can make an own class for it and run it **after** our optimization loop or we do it during code generation.
